### PR TITLE
Eliminate race condition

### PR DESCRIPTION
**Pull request by mattkrick**
Problem: Map would sometimes only load the upper left quarter tile. This was not always fixed by a refresh. Also, elements appended to the map (such as an autocomplete search bar) would sometimes not be appended, or they would be appended but remain outside the map as well. This was always fixed with a refresh.

Root cause: Race condition. There's 3 events going on here:
1. Load - before the load of the script tag
2. Create - before template is rendered (Spacebars variables)
3. Ready - Before the callback to modify the map, add listeners, etc.

Sometimes, ready would fire before created because both were only dependent on load.
This can be tested by a `console.log` inside `loaded()` and `ready()`. In my case, I front-loaded a TON of stuff to ensure failure & when I would refresh, it would hit `ready` before `loaded`. From a link or external load, it would hit `loaded` before `ready`. I stored this flag in a reactive dict to enable multiple maps on the same page.

### CODE REVIEW

**Comment by dburles** [comment]
Hey thanks @mattkrick I would really like a reproduction I can test with myself before merging as I wasn't able to reproduce the issue.

**Comment by dburles** [comment]
@mattkrick I've just updated the package to make use of google maps `tilesloaded` event to fire the callbacks, would you mind seeing if this corrects the issues? It's working great with what I've tested.

**Comment by mattkrick** [comment]
Thanks, & sorry for the late reply, I still haven't been able to make a faithful reproduction of the race in open source, but so far so good w/ the pull request version.

Trying out this package update I get a gray box & an "x is undefined" coming from the google maps minified file on every click and mousemove event inside that gray box where the tiles should be. I do some weird stuff to the map though, so I'm probably an edge case & don't mind rolling my own.

**Comment by dburles** [comment]
I think I'll close the PR for now, but do let me know if you figure out a simple repro of that strangeness :)

**Pull request closed without merging**
